### ISSUE TITLE
Require config keys to start with a `+` in `dbt_project.yml`

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-cleanup#10]
Make this allowed in `dbt_project.yml`
```
models:
  +enabled: True
  <path>:
    +enabled: True
```

But not this
```
models:
  enabled: True
  <path>:
    enabled: True
```

Couple of things to keep in mind:

- for entries without a `+`, check if they are paths
  - if they aren't path and not a config either, add error logs
  - we'd need to check paths for packages as well (so know the packages paths too)
