### ISSUE TITLE
Best-effort fix of typos

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-cleanup#9]
If there's a known key (say, `description`) which is not present in a model but there's a similarly-spelled invalid key present (say, `desciption`), it's probably safe to update the spelling instead of moving it to a config. 

"similarly-spelled" is left as an exercise to the implementor, _waves hands wildly_ Levenshtein distance or whatever 

Before: 
```yml
models: 
  - name: my_model 
    desciption: "This is a very useful model which does things"

  - name: my_second_model
    desciption: "idk what this is doing here"
    description: "This is the true descriptor of the model"
```
After:  
```yml
models: 
  - name: my_model 
    description: "This is a very useful model which does things"

  - name: my_second_model
    description: "This is the true descriptor of the model"
    config: 
      meta: 
        desciption: "idk what this is doing here"
```
